# Generated by Django 3.2.6 on 2021-08-31 02:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('region', models.CharField(choices=[('1', 'Northern'), ('2', 'Rocky Mountain'), ('3', 'Southwestern'), ('4', 'Intermountain'), ('5', 'Pacific Southwest'), ('6', 'Pacific Northwest'), ('8', 'Southern'), ('9', 'Eastern'), ('10', 'Alaska'), ('WO', 'Washington Office')], default='WO', max_length=4)),
                ('base', models.CharField(blank=True, max_length=20)),
                ('office_phone', models.CharField(blank=True, max_length=12)),
                ('cell_phone', models.CharField(blank=True, max_length=12)),
                ('date_of_hire', models.DateField(blank=True, null=True)),
                ('pilot_cert_number', models.CharField(blank=True, max_length=20)),
                ('atp', models.BooleanField(default=False)),
                ('cfi', models.BooleanField(default=False)),
                ('cfii', models.BooleanField(default=False)),
                ('mei', models.BooleanField(default=False)),
                ('commercial_rating', models.BooleanField(default=False)),
                ('medical_class', models.IntegerField(blank=True, null=True)),
                ('date_of_medical', models.DateField(blank=True, null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_captain', models.BooleanField(default=False)),
                ('smokejumper_msn_eval_date', models.DateField(blank=True, null=True)),
                ('equipment_eval_date', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_supervisor', models.ForeignKey(limit_choices_to={'is_supervisor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MsnQual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(choices=[('LP', 'Leadplane'), ('SJ', 'Smokejumper'), ('PP', 'Pilot Proficiency'), ('AD', 'Administrative'), ('OT', 'Civilian/Military'), ('AA', 'Air Attack'), ('MT', 'Maintenance'), ('LOG', 'Logistics'), ('ASM', 'Aerial Supervision Module'), ('HC', 'Helicopter'), ('IR', 'Infrared'), ('RC', 'Recon'), ('PH', 'Photo'), ('BC', 'Back Country')], max_length=20)),
                ('mission_check_date', models.DateField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcftQual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acft', models.CharField(choices=[('SD-3', 'Sherpa'), ('KA', 'King Air'), ('206', 'C-206')], max_length=15)),
                ('acft_check_date', models.DateField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
