# Generated by Django 3.2.6 on 2021-09-30 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_user_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_supervisor',
            field=models.ForeignKey(default=5, limit_choices_to={'is_supervisor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
