# Generated by Django 3.2.6 on 2021-10-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_log', '0009_auto_20210930_0307'),
        ('accounts', '0006_alter_customuser_user_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='flights',
            field=models.ManyToManyField(to='pilot_log.FlightDetail'),
        ),
    ]
