# Generated by Django 3.2.6 on 2021-09-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('SD-3', 'Sherpa'), ('KA', 'King Air'), ('206', 'C-206')], max_length=16),
        ),
    ]
