# Generated by Django 3.2.6 on 2021-09-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_log', '0002_alter_aircraft_aircraft_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('SD-3', 'Sherpa'), ('KA', 'King Air'), ('206', 'C-206')], max_length=15),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
