# Generated by Django 3.2.6 on 2021-09-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_log', '0003_auto_20210901_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetail',
            name='act_instrument_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='day_landings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='holds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='instructor_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='instrument_appchs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='night_landings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='night_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='pic_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='sic_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='sim_instrument_time',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
