# Generated by Django 3.2.6 on 2021-09-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_log', '0004_auto_20210901_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightdetail',
            options={'ordering': ['-date_of_flight']},
        ),
    ]
