# Generated by Django 3.2.6 on 2021-09-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_log', '0005_alter_flightdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightdetail',
            options={'get_latest_by': 'date_of_flight', 'ordering': ['-date_of_flight']},
        ),
    ]
