# Generated by Django 3.2.6 on 2021-09-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_log', '0006_alter_flightdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetail',
            name='arrival_ICAO',
            field=models.CharField(default='KMSO', max_length=4),
        ),
        migrations.AlterField(
            model_name='flightdetail',
            name='depart_ICAO',
            field=models.CharField(default='KMSO', max_length=4),
        ),
    ]
