# Generated by Django 3.2.6 on 2021-09-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_log', '0007_auto_20210920_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetail',
            name='total_time',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
